behaviors:
  Tank:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 1.0e-3
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 5120

//Continous angle and power
//Trained for aprox 2 hours, could hit 1/10 shots from a fixed pos.
//linear reward based on distance to target 
//Mathf.Clamp(-dist / 8 + 1, -1, 1) per shot;
//Episode consists of 100 shots
//Seems faulty but learned