behaviors:
  Tank:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 3200
      learning_rate: 1.0e-3
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    self_play:
      save_steps: 3200
      team_change: 6400
      swap_steps: 3200
      window: 3
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 3200
engine_settings:
  width: 84
  height: 84
  quality_level: 10
  time_scale: 50
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true

//Self play
//Discrete angles and power
//Reward function +1 win, -1 lose, 0 tie
//Episode is one match consisting of 10 shots each