behaviors:
  Tank:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1600
      learning_rate: 1.0e-2
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 32
      num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 3200
engine_settings:
  width: 30
  height: 30
  quality_level: 10
  time_scale: 1000
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true